---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: challenge-bot
  namespace: test
  labels:
    app: challenge-bot
    role: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challenge-bot
      role: agent
  template:
    metadata:
      labels:
        app: challenge-bot
        role: agent
    spec:
      containers:
      - name: challenge-bot
        image: 856572510817.dkr.ecr.eu-west-1.amazonaws.com/challenge-bot:develop
        imagePullPolicy: Always
        env:
        - name: NODE_ENV
          value: development
        - name: NAHMII_BASE_URL
          value: api2.dev.hubii.net
        - name: ETHEREUM_NODE_URL
          value: http://geth-ropsten.dev.hubii.net
        - name: CHALLENGE_BOT_UTCADDRESS
          value: 3caac75eaf3860ed355ca260b01b396985a40a70
        - name: CHALLENGE_BOT_UTCSECRET
          valueFrom:
            secretKeyRef:
              name: testnet-keyfile
              key: secret
        - name: CHALLENGE_BOT_APPID
          valueFrom:
            secretKeyRef:
              name: payment-engine
              key: appid
        - name: CHALLENGE_BOT_APPSECRET
          valueFrom:
            secretKeyRef:
              name: payment-engine
              key: appsecret
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        volumeMounts:
        - name: keystore
          mountPath: /app/keystore
      volumes:
      - name: keystore
        secret:
          secretName: testnet-keyfile
