---
apiVersion: v1
kind: Service
metadata:
  name: challenge-bot
  labels:
    app: challenge-bot
    role: agent
spec:
  type: ClusterIP
  selector:
    app: challenge-bot
    role: agent
  ports:
  - name: metrics
    protocol: TCP
    port: 8079
    targetPort: 8079

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: challenge-bot
  labels:
    app: challenge-bot
    role: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challenge-bot
      role: agent
  template:
    metadata:
      labels:
        app: challenge-bot
        role: agent
    spec:
      containers:
      - name: challenge-bot
        image: 856572510817.dkr.ecr.eu-west-1.amazonaws.com/challenge-bot:v291
        imagePullPolicy: Always
        env:
        - name: METRICS_PORT
          value: "8079"
        - name: NODE_ENV
          value: production
        - name: NAHMII_BASE_URL
          value: api.nahmii.io
        - name: ETHEREUM_GAS_LIMIT
          value: '2000000'
        - name: ETHEREUM_NODE_URL
          value: http://ethereum.hubii.com:8545
        - name: CHALLENGE_BOT_UTCADDRESS
          value: ded8dc6316d23ce0bb5b5004b8e6f7018f48dbb8
        - name: CHALLENGE_BOT_UTCSECRET
          valueFrom:
            secretKeyRef:
              name: challengebot-keyfile
              key: secret
        - name: CHALLENGE_BOT_APPID
          valueFrom:
            secretKeyRef:
              name: challengebot-credentials
              key: appid
        - name: CHALLENGE_BOT_APPSECRET
          valueFrom:
            secretKeyRef:
              name: challengebot-credentials
              key: appsecret
        volumeMounts:
        - name: keystore
          mountPath: /app/keystore
      volumes:
      - name: keystore
        secret:
          secretName: challengebot-keyfile
