---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: challenge-bot
  labels:
    app: challenge-bot
    role: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challenge-bot
      role: agent
  template:
    metadata:
      labels:
        app: challenge-bot
        role: agent
    spec:
      containers:
      - name: challenge-bot
        image: 856572510817.dkr.ecr.eu-west-1.amazonaws.com/challenge-bot:v38
        imagePullPolicy: Always
        env:
        - name: NAHMII_API_ROOT
          value: api2.dev.hubii.net
        - name: NODE_ENV
          value: production
        - name: CHALLENGE_BOT_ADDRESS
          valueFrom:
            secretKeyRef:
              name: challenge-bot
              key: appid
        - name: CHALLENGE_BOT_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: challenge-bot
              key: appsecret
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
