---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: challenge-bot
  labels:
    app: challenge-bot
    role: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challenge-bot
      role: agent
  template:
    metadata:
      labels:
        app: challenge-bot
        role: agent
    spec:
      containers:
      - name: challenge-bot
        image: 856572510817.dkr.ecr.eu-west-1.amazonaws.com/challenge-bot:v38
        imagePullPolicy: Always
        env:
        - name: NODE_ENV
          value: production
        - name: NAHMII_BASE_URL
          value: api.nahmii.io
        - name: ETHEREUM_NODE_URL
          value: http://ethereum.hubii.com
        - name: CHALLENGE_BOT_UTCADDRESS
          value: 0xXXXXXXXXXXXXXXXXXX?
        - name: CHALLENGE_BOT_UTCSECRET
          valueFrom:
            secretKeyRef:
              name: challenge-bot
              key: utcsecret
        - name: CHALLENGE_BOT_APPID
          valueFrom:
            secretKeyRef:
              name: challenge-bot
              key: appid
        - name: CHALLENGE_BOT_APPSECRET
          valueFrom:
            secretKeyRef:
              name: challenge-bot
              key: appsecret
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        volumeMounts:
        - name: challenge-bot-keystore
          mountPath: /app/keystore
      volumes:
      - name: challenge-bot-keystore
        secret:
          secretName: challenge-bot-utcfile
